repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-toml
    -   id: check-added-large-files
    -   id: mixed-line-ending
    -   id: check-merge-conflict
    -   id: check-ast
    -   id: requirements-txt-fixer
repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.7.1
  hooks:
    - id: ruff
      args: [ --fix ]
    - id: ruff-format
-   repo: https://github.com/pappasam/toml-sort
    rev: v0.23.1
    hooks:
    -   id: toml-sort
        args:
            - --in-place
            - --all
-   repo: https://github.com/asottile/pyupgrade
    rev: v3.10.1
    hooks:
    -   id: pyupgrade
        args:
            - --py311-plus
